name: Artifact Demo Pipeline

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Create Report
        run: |
          echo "Build Successful" > report.txt
          date >> report.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-report
          path: report.txt
